name: vulnerability scan workflow

on: [push, workflow_dispatch]

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v3
            
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: 'adopt'
                
          - name: setup-cocoapods
            run: |
                 sudo apt update
                 sudo apt install ruby-full
                 sudo gem install cocoapods -v 1.12.1
        
          - name: Download the meterian CLI
            run: wget -N https://www.meterian.io/downloads/meterian-cli.jar
            
          - name: Scan project with the Meterian client
            run: java -jar meterian-cli.jar
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
